// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.5
// source: proto/rpc.proto

package rpcpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SessionChannel int32

const (
	SessionChannel_SESSION_CHANNEL_UNSPECIFIED SessionChannel = 0
	SessionChannel_RADIO                       SessionChannel = 1
	SessionChannel_SATELLITE                   SessionChannel = 2
	SessionChannel_CELLULAR                    SessionChannel = 3
	SessionChannel_MESH                        SessionChannel = 4
)

// Enum value maps for SessionChannel.
var (
	SessionChannel_name = map[int32]string{
		0: "SESSION_CHANNEL_UNSPECIFIED",
		1: "RADIO",
		2: "SATELLITE",
		3: "CELLULAR",
		4: "MESH",
	}
	SessionChannel_value = map[string]int32{
		"SESSION_CHANNEL_UNSPECIFIED": 0,
		"RADIO":                       1,
		"SATELLITE":                   2,
		"CELLULAR":                    3,
		"MESH":                        4,
	}
)

func (x SessionChannel) Enum() *SessionChannel {
	p := new(SessionChannel)
	*p = x
	return p
}

func (x SessionChannel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionChannel) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_rpc_proto_enumTypes[0].Descriptor()
}

func (SessionChannel) Type() protoreflect.EnumType {
	return &file_proto_rpc_proto_enumTypes[0]
}

func (x SessionChannel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionChannel.Descriptor instead.
func (SessionChannel) EnumDescriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{0}
}

// Envelope is the top-level payload carried inside every IPv4Datagram.
// request_id correlates async responses back to their originating request.
// namespace must equal EnvelopeNamespace; packets without it are discarded.
type Envelope struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Namespace string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	RequestId uint32                 `protobuf:"varint,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	SessionId uint64                 `protobuf:"varint,6,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Envelope_Request
	//	*Envelope_Response
	Payload       isEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_proto_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Envelope) GetRequestId() uint32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *Envelope) GetSessionId() uint64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *Envelope) GetPayload() isEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetRequest() *RpcRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Request); ok {
			return x.Request
		}
	}
	return nil
}

func (x *Envelope) GetResponse() *RpcResponse {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Response); ok {
			return x.Response
		}
	}
	return nil
}

type isEnvelope_Payload interface {
	isEnvelope_Payload()
}

type Envelope_Request struct {
	Request *RpcRequest `protobuf:"bytes,3,opt,name=request,proto3,oneof"`
}

type Envelope_Response struct {
	Response *RpcResponse `protobuf:"bytes,4,opt,name=response,proto3,oneof"`
}

func (*Envelope_Request) isEnvelope_Payload() {}

func (*Envelope_Response) isEnvelope_Payload() {}

// RpcRequest carries a single method call. Add new methods here as a new oneof field.
type RpcRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Method:
	//
	//	*RpcRequest_Exec
	//	*RpcRequest_Connect
	//	*RpcRequest_Discover
	//	*RpcRequest_Ping
	//	*RpcRequest_Disconnect
	Method        isRpcRequest_Method `protobuf_oneof:"method"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcRequest) Reset() {
	*x = RpcRequest{}
	mi := &file_proto_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcRequest) ProtoMessage() {}

func (x *RpcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcRequest.ProtoReflect.Descriptor instead.
func (*RpcRequest) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *RpcRequest) GetMethod() isRpcRequest_Method {
	if x != nil {
		return x.Method
	}
	return nil
}

func (x *RpcRequest) GetExec() *ExecRequest {
	if x != nil {
		if x, ok := x.Method.(*RpcRequest_Exec); ok {
			return x.Exec
		}
	}
	return nil
}

func (x *RpcRequest) GetConnect() *ConnectRequest {
	if x != nil {
		if x, ok := x.Method.(*RpcRequest_Connect); ok {
			return x.Connect
		}
	}
	return nil
}

func (x *RpcRequest) GetDiscover() *DiscoverRequest {
	if x != nil {
		if x, ok := x.Method.(*RpcRequest_Discover); ok {
			return x.Discover
		}
	}
	return nil
}

func (x *RpcRequest) GetPing() *PingRequest {
	if x != nil {
		if x, ok := x.Method.(*RpcRequest_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *RpcRequest) GetDisconnect() *DisconnectRequest {
	if x != nil {
		if x, ok := x.Method.(*RpcRequest_Disconnect); ok {
			return x.Disconnect
		}
	}
	return nil
}

type isRpcRequest_Method interface {
	isRpcRequest_Method()
}

type RpcRequest_Exec struct {
	Exec *ExecRequest `protobuf:"bytes,1,opt,name=exec,proto3,oneof"`
}

type RpcRequest_Connect struct {
	Connect *ConnectRequest `protobuf:"bytes,2,opt,name=connect,proto3,oneof"`
}

type RpcRequest_Discover struct {
	Discover *DiscoverRequest `protobuf:"bytes,3,opt,name=discover,proto3,oneof"`
}

type RpcRequest_Ping struct {
	Ping *PingRequest `protobuf:"bytes,4,opt,name=ping,proto3,oneof"`
}

type RpcRequest_Disconnect struct {
	Disconnect *DisconnectRequest `protobuf:"bytes,6,opt,name=disconnect,proto3,oneof"`
}

func (*RpcRequest_Exec) isRpcRequest_Method() {}

func (*RpcRequest_Connect) isRpcRequest_Method() {}

func (*RpcRequest_Discover) isRpcRequest_Method() {}

func (*RpcRequest_Ping) isRpcRequest_Method() {}

func (*RpcRequest_Disconnect) isRpcRequest_Method() {}

// RpcResponse carries the result of an RpcRequest or a transport-level error.
type RpcResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*RpcResponse_Exec
	//	*RpcResponse_Error
	//	*RpcResponse_Connect
	//	*RpcResponse_Discover
	//	*RpcResponse_Ping
	Result        isRpcResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcResponse) Reset() {
	*x = RpcResponse{}
	mi := &file_proto_rpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcResponse) ProtoMessage() {}

func (x *RpcResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcResponse.ProtoReflect.Descriptor instead.
func (*RpcResponse) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *RpcResponse) GetResult() isRpcResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *RpcResponse) GetExec() *ExecResponse {
	if x != nil {
		if x, ok := x.Result.(*RpcResponse_Exec); ok {
			return x.Exec
		}
	}
	return nil
}

func (x *RpcResponse) GetError() *RpcError {
	if x != nil {
		if x, ok := x.Result.(*RpcResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *RpcResponse) GetConnect() *ConnectResponse {
	if x != nil {
		if x, ok := x.Result.(*RpcResponse_Connect); ok {
			return x.Connect
		}
	}
	return nil
}

func (x *RpcResponse) GetDiscover() *DiscoverResponse {
	if x != nil {
		if x, ok := x.Result.(*RpcResponse_Discover); ok {
			return x.Discover
		}
	}
	return nil
}

func (x *RpcResponse) GetPing() *PingResponse {
	if x != nil {
		if x, ok := x.Result.(*RpcResponse_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

type isRpcResponse_Result interface {
	isRpcResponse_Result()
}

type RpcResponse_Exec struct {
	Exec *ExecResponse `protobuf:"bytes,1,opt,name=exec,proto3,oneof"`
}

type RpcResponse_Error struct {
	Error *RpcError `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

type RpcResponse_Connect struct {
	Connect *ConnectResponse `protobuf:"bytes,3,opt,name=connect,proto3,oneof"`
}

type RpcResponse_Discover struct {
	Discover *DiscoverResponse `protobuf:"bytes,4,opt,name=discover,proto3,oneof"`
}

type RpcResponse_Ping struct {
	Ping *PingResponse `protobuf:"bytes,5,opt,name=ping,proto3,oneof"`
}

func (*RpcResponse_Exec) isRpcResponse_Result() {}

func (*RpcResponse_Error) isRpcResponse_Result() {}

func (*RpcResponse_Connect) isRpcResponse_Result() {}

func (*RpcResponse_Discover) isRpcResponse_Result() {}

func (*RpcResponse_Ping) isRpcResponse_Result() {}

type ExecRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_proto_rpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *ExecRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type ExecResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        string                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	ExitCode      int32                  `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Truncated     bool                   `protobuf:"varint,3,opt,name=truncated,proto3" json:"truncated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecResponse) Reset() {
	*x = ExecResponse{}
	mi := &file_proto_rpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResponse) ProtoMessage() {}

func (x *ExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResponse.ProtoReflect.Descriptor instead.
func (*ExecResponse) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{4}
}

func (x *ExecResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *ExecResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecResponse) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

type ConnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     uint64                 `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Channels      []SessionChannel       `protobuf:"varint,2,rep,packed,name=channels,proto3,enum=somewear.rpc.SessionChannel" json:"channels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	mi := &file_proto_rpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{5}
}

func (x *ConnectRequest) GetSessionId() uint64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *ConnectRequest) GetChannels() []SessionChannel {
	if x != nil {
		return x.Channels
	}
	return nil
}

type ConnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	IpAddresses   []string               `protobuf:"bytes,2,rep,name=ip_addresses,json=ipAddresses,proto3" json:"ip_addresses,omitempty"`
	Arch          string                 `protobuf:"bytes,3,opt,name=arch,proto3" json:"arch,omitempty"`
	CpuModel      string                 `protobuf:"bytes,4,opt,name=cpu_model,json=cpuModel,proto3" json:"cpu_model,omitempty"`
	CpuCount      int32                  `protobuf:"varint,5,opt,name=cpu_count,json=cpuCount,proto3" json:"cpu_count,omitempty"`
	SessionId     uint64                 `protobuf:"varint,6,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Channels      []SessionChannel       `protobuf:"varint,7,rep,packed,name=channels,proto3,enum=somewear.rpc.SessionChannel" json:"channels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectResponse) Reset() {
	*x = ConnectResponse{}
	mi := &file_proto_rpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectResponse) ProtoMessage() {}

func (x *ConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectResponse.ProtoReflect.Descriptor instead.
func (*ConnectResponse) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{6}
}

func (x *ConnectResponse) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *ConnectResponse) GetIpAddresses() []string {
	if x != nil {
		return x.IpAddresses
	}
	return nil
}

func (x *ConnectResponse) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *ConnectResponse) GetCpuModel() string {
	if x != nil {
		return x.CpuModel
	}
	return ""
}

func (x *ConnectResponse) GetCpuCount() int32 {
	if x != nil {
		return x.CpuCount
	}
	return 0
}

func (x *ConnectResponse) GetSessionId() uint64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *ConnectResponse) GetChannels() []SessionChannel {
	if x != nil {
		return x.Channels
	}
	return nil
}

type DisconnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectRequest) Reset() {
	*x = DisconnectRequest{}
	mi := &file_proto_rpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectRequest) ProtoMessage() {}

func (x *DisconnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectRequest.ProtoReflect.Descriptor instead.
func (*DisconnectRequest) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{7}
}

// The four ping timestamps use Unix milliseconds so each direction can be
// shown when peer clocks are synchronized. RTT only uses the client's clock.
type PingRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ClientSendUnixMillis int64                  `protobuf:"varint,1,opt,name=client_send_unix_millis,json=clientSendUnixMillis,proto3" json:"client_send_unix_millis,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_proto_rpc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{8}
}

func (x *PingRequest) GetClientSendUnixMillis() int64 {
	if x != nil {
		return x.ClientSendUnixMillis
	}
	return 0
}

type PingResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	TargetReceiveUnixMillis int64                  `protobuf:"varint,1,opt,name=target_receive_unix_millis,json=targetReceiveUnixMillis,proto3" json:"target_receive_unix_millis,omitempty"`
	TargetSendUnixMillis    int64                  `protobuf:"varint,2,opt,name=target_send_unix_millis,json=targetSendUnixMillis,proto3" json:"target_send_unix_millis,omitempty"`
	// Echoed from Beam's inbound webhook timestamp. Together with the source
	// account and package type, this reconstructs the request datagram ID.
	ClientPackageSendUnixSeconds int64 `protobuf:"varint,3,opt,name=client_package_send_unix_seconds,json=clientPackageSendUnixSeconds,proto3" json:"client_package_send_unix_seconds,omitempty"`
	ClientAccountId              int64 `protobuf:"varint,4,opt,name=client_account_id,json=clientAccountId,proto3" json:"client_account_id,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_proto_rpc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{9}
}

func (x *PingResponse) GetTargetReceiveUnixMillis() int64 {
	if x != nil {
		return x.TargetReceiveUnixMillis
	}
	return 0
}

func (x *PingResponse) GetTargetSendUnixMillis() int64 {
	if x != nil {
		return x.TargetSendUnixMillis
	}
	return 0
}

func (x *PingResponse) GetClientPackageSendUnixSeconds() int64 {
	if x != nil {
		return x.ClientPackageSendUnixSeconds
	}
	return 0
}

func (x *PingResponse) GetClientAccountId() int64 {
	if x != nil {
		return x.ClientAccountId
	}
	return 0
}

// DiscoverRequest is broadcast to a workspace. response_jitter_ms asks peers
// to spread their replies over a bounded window instead of responding at once.
type DiscoverRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ResponseJitterMs uint32                 `protobuf:"varint,1,opt,name=response_jitter_ms,json=responseJitterMs,proto3" json:"response_jitter_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DiscoverRequest) Reset() {
	*x = DiscoverRequest{}
	mi := &file_proto_rpc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverRequest) ProtoMessage() {}

func (x *DiscoverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverRequest.ProtoReflect.Descriptor instead.
func (*DiscoverRequest) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{10}
}

func (x *DiscoverRequest) GetResponseJitterMs() uint32 {
	if x != nil {
		return x.ResponseJitterMs
	}
	return 0
}

// The sender's Beam account ID is deliberately omitted because Beam supplies
// it in the webhook metadata. Keep this response small for satellite links.
type DiscoverResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	Hostname        string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Arch            string                 `protobuf:"bytes,3,opt,name=arch,proto3" json:"arch,omitempty"`
	Capabilities    uint32                 `protobuf:"varint,4,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DiscoverResponse) Reset() {
	*x = DiscoverResponse{}
	mi := &file_proto_rpc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverResponse) ProtoMessage() {}

func (x *DiscoverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverResponse.ProtoReflect.Descriptor instead.
func (*DiscoverResponse) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{11}
}

func (x *DiscoverResponse) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *DiscoverResponse) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *DiscoverResponse) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *DiscoverResponse) GetCapabilities() uint32 {
	if x != nil {
		return x.Capabilities
	}
	return 0
}

type RpcError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcError) Reset() {
	*x = RpcError{}
	mi := &file_proto_rpc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcError) ProtoMessage() {}

func (x *RpcError) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcError.ProtoReflect.Descriptor instead.
func (*RpcError) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proto_rawDescGZIP(), []int{12}
}

func (x *RpcError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_rpc_proto protoreflect.FileDescriptor

const file_proto_rpc_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/rpc.proto\x12\fsomewear.rpc\"\xe0\x01\n" +
	"\bEnvelope\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\rR\trequestId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x06 \x01(\x04R\tsessionId\x124\n" +
	"\arequest\x18\x03 \x01(\v2\x18.somewear.rpc.RpcRequestH\x00R\arequest\x127\n" +
	"\bresponse\x18\x04 \x01(\v2\x19.somewear.rpc.RpcResponseH\x00R\bresponseB\t\n" +
	"\apayload\"\xb2\x02\n" +
	"\n" +
	"RpcRequest\x12/\n" +
	"\x04exec\x18\x01 \x01(\v2\x19.somewear.rpc.ExecRequestH\x00R\x04exec\x128\n" +
	"\aconnect\x18\x02 \x01(\v2\x1c.somewear.rpc.ConnectRequestH\x00R\aconnect\x12;\n" +
	"\bdiscover\x18\x03 \x01(\v2\x1d.somewear.rpc.DiscoverRequestH\x00R\bdiscover\x12/\n" +
	"\x04ping\x18\x04 \x01(\v2\x19.somewear.rpc.PingRequestH\x00R\x04ping\x12A\n" +
	"\n" +
	"disconnect\x18\x06 \x01(\v2\x1f.somewear.rpc.DisconnectRequestH\x00R\n" +
	"disconnectB\b\n" +
	"\x06method\"\xa4\x02\n" +
	"\vRpcResponse\x120\n" +
	"\x04exec\x18\x01 \x01(\v2\x1a.somewear.rpc.ExecResponseH\x00R\x04exec\x12.\n" +
	"\x05error\x18\x02 \x01(\v2\x16.somewear.rpc.RpcErrorH\x00R\x05error\x129\n" +
	"\aconnect\x18\x03 \x01(\v2\x1d.somewear.rpc.ConnectResponseH\x00R\aconnect\x12<\n" +
	"\bdiscover\x18\x04 \x01(\v2\x1e.somewear.rpc.DiscoverResponseH\x00R\bdiscover\x120\n" +
	"\x04ping\x18\x05 \x01(\v2\x1a.somewear.rpc.PingResponseH\x00R\x04pingB\b\n" +
	"\x06result\"'\n" +
	"\vExecRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\"a\n" +
	"\fExecResponse\x12\x16\n" +
	"\x06output\x18\x01 \x01(\tR\x06output\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode\x12\x1c\n" +
	"\ttruncated\x18\x03 \x01(\bR\ttruncated\"i\n" +
	"\x0eConnectRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\x04R\tsessionId\x128\n" +
	"\bchannels\x18\x02 \x03(\x0e2\x1c.somewear.rpc.SessionChannelR\bchannels\"\xf7\x01\n" +
	"\x0fConnectResponse\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12!\n" +
	"\fip_addresses\x18\x02 \x03(\tR\vipAddresses\x12\x12\n" +
	"\x04arch\x18\x03 \x01(\tR\x04arch\x12\x1b\n" +
	"\tcpu_model\x18\x04 \x01(\tR\bcpuModel\x12\x1b\n" +
	"\tcpu_count\x18\x05 \x01(\x05R\bcpuCount\x12\x1d\n" +
	"\n" +
	"session_id\x18\x06 \x01(\x04R\tsessionId\x128\n" +
	"\bchannels\x18\a \x03(\x0e2\x1c.somewear.rpc.SessionChannelR\bchannels\"\x13\n" +
	"\x11DisconnectRequest\"D\n" +
	"\vPingRequest\x125\n" +
	"\x17client_send_unix_millis\x18\x01 \x01(\x03R\x14clientSendUnixMillis\"\xf6\x01\n" +
	"\fPingResponse\x12;\n" +
	"\x1atarget_receive_unix_millis\x18\x01 \x01(\x03R\x17targetReceiveUnixMillis\x125\n" +
	"\x17target_send_unix_millis\x18\x02 \x01(\x03R\x14targetSendUnixMillis\x12F\n" +
	" client_package_send_unix_seconds\x18\x03 \x01(\x03R\x1cclientPackageSendUnixSeconds\x12*\n" +
	"\x11client_account_id\x18\x04 \x01(\x03R\x0fclientAccountId\"?\n" +
	"\x0fDiscoverRequest\x12,\n" +
	"\x12response_jitter_ms\x18\x01 \x01(\rR\x10responseJitterMs\"\x91\x01\n" +
	"\x10DiscoverResponse\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x12\n" +
	"\x04arch\x18\x03 \x01(\tR\x04arch\x12\"\n" +
	"\fcapabilities\x18\x04 \x01(\rR\fcapabilities\"$\n" +
	"\bRpcError\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage*c\n" +
	"\x0eSessionChannel\x12\x1f\n" +
	"\x1bSESSION_CHANNEL_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05RADIO\x10\x01\x12\r\n" +
	"\tSATELLITE\x10\x02\x12\f\n" +
	"\bCELLULAR\x10\x03\x12\b\n" +
	"\x04MESH\x10\x04B\x1aZ\x18somewear/rpc/proto;rpcpbb\x06proto3"

var (
	file_proto_rpc_proto_rawDescOnce sync.Once
	file_proto_rpc_proto_rawDescData []byte
)

func file_proto_rpc_proto_rawDescGZIP() []byte {
	file_proto_rpc_proto_rawDescOnce.Do(func() {
		file_proto_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_rpc_proto_rawDesc), len(file_proto_rpc_proto_rawDesc)))
	})
	return file_proto_rpc_proto_rawDescData
}

var file_proto_rpc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_rpc_proto_goTypes = []any{
	(SessionChannel)(0),       // 0: somewear.rpc.SessionChannel
	(*Envelope)(nil),          // 1: somewear.rpc.Envelope
	(*RpcRequest)(nil),        // 2: somewear.rpc.RpcRequest
	(*RpcResponse)(nil),       // 3: somewear.rpc.RpcResponse
	(*ExecRequest)(nil),       // 4: somewear.rpc.ExecRequest
	(*ExecResponse)(nil),      // 5: somewear.rpc.ExecResponse
	(*ConnectRequest)(nil),    // 6: somewear.rpc.ConnectRequest
	(*ConnectResponse)(nil),   // 7: somewear.rpc.ConnectResponse
	(*DisconnectRequest)(nil), // 8: somewear.rpc.DisconnectRequest
	(*PingRequest)(nil),       // 9: somewear.rpc.PingRequest
	(*PingResponse)(nil),      // 10: somewear.rpc.PingResponse
	(*DiscoverRequest)(nil),   // 11: somewear.rpc.DiscoverRequest
	(*DiscoverResponse)(nil),  // 12: somewear.rpc.DiscoverResponse
	(*RpcError)(nil),          // 13: somewear.rpc.RpcError
}
var file_proto_rpc_proto_depIdxs = []int32{
	2,  // 0: somewear.rpc.Envelope.request:type_name -> somewear.rpc.RpcRequest
	3,  // 1: somewear.rpc.Envelope.response:type_name -> somewear.rpc.RpcResponse
	4,  // 2: somewear.rpc.RpcRequest.exec:type_name -> somewear.rpc.ExecRequest
	6,  // 3: somewear.rpc.RpcRequest.connect:type_name -> somewear.rpc.ConnectRequest
	11, // 4: somewear.rpc.RpcRequest.discover:type_name -> somewear.rpc.DiscoverRequest
	9,  // 5: somewear.rpc.RpcRequest.ping:type_name -> somewear.rpc.PingRequest
	8,  // 6: somewear.rpc.RpcRequest.disconnect:type_name -> somewear.rpc.DisconnectRequest
	5,  // 7: somewear.rpc.RpcResponse.exec:type_name -> somewear.rpc.ExecResponse
	13, // 8: somewear.rpc.RpcResponse.error:type_name -> somewear.rpc.RpcError
	7,  // 9: somewear.rpc.RpcResponse.connect:type_name -> somewear.rpc.ConnectResponse
	12, // 10: somewear.rpc.RpcResponse.discover:type_name -> somewear.rpc.DiscoverResponse
	10, // 11: somewear.rpc.RpcResponse.ping:type_name -> somewear.rpc.PingResponse
	0,  // 12: somewear.rpc.ConnectRequest.channels:type_name -> somewear.rpc.SessionChannel
	0,  // 13: somewear.rpc.ConnectResponse.channels:type_name -> somewear.rpc.SessionChannel
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_proto_rpc_proto_init() }
func file_proto_rpc_proto_init() {
	if File_proto_rpc_proto != nil {
		return
	}
	file_proto_rpc_proto_msgTypes[0].OneofWrappers = []any{
		(*Envelope_Request)(nil),
		(*Envelope_Response)(nil),
	}
	file_proto_rpc_proto_msgTypes[1].OneofWrappers = []any{
		(*RpcRequest_Exec)(nil),
		(*RpcRequest_Connect)(nil),
		(*RpcRequest_Discover)(nil),
		(*RpcRequest_Ping)(nil),
		(*RpcRequest_Disconnect)(nil),
	}
	file_proto_rpc_proto_msgTypes[2].OneofWrappers = []any{
		(*RpcResponse_Exec)(nil),
		(*RpcResponse_Error)(nil),
		(*RpcResponse_Connect)(nil),
		(*RpcResponse_Discover)(nil),
		(*RpcResponse_Ping)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_rpc_proto_rawDesc), len(file_proto_rpc_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_rpc_proto_goTypes,
		DependencyIndexes: file_proto_rpc_proto_depIdxs,
		EnumInfos:         file_proto_rpc_proto_enumTypes,
		MessageInfos:      file_proto_rpc_proto_msgTypes,
	}.Build()
	File_proto_rpc_proto = out.File
	file_proto_rpc_proto_goTypes = nil
	file_proto_rpc_proto_depIdxs = nil
}
